feature/data-passing-with-redux
EgijaLocmele/React-training-task pull request #5
Opened 2021-09-10 09:56 UTC by EgijaLocmele

Changed data passing from props to using Redux logic

2021-09-10 10:46 UTC, YuraLeo94 requested changes

2021-09-10 10:46 UTC, YuraLeo94 commented on src/features/productDetails/ProductDetails.js
>    let { itemId } = useParams()
Why not const? Do you change in this file value of `itemId`?

2021-09-10 10:46 UTC, YuraLeo94 commented on src/features/productList/ProductList.js
> +  console.log(products)
Please remove `console.log(products)`

2021-09-13 07:46 UTC, leleleadele commented on src/App.js
> +          <ProductList products={product} />
You're passing only one item to the list or how does this work?

2021-09-13 07:57 UTC, EgijaLocmele commented on src/App.js
> +          <ProductList products={product} />
No, it's basically passing data that is accessed with useSelector(), so not only one item but everything

2021-09-13 08:01 UTC, leleleadele commented on src/features/productDetails/ProductDetails.js
> +const ProductDetails = (props) => {
you can write `const ProductDetails = ({ products }) => ..` instead

2021-09-13 08:05 UTC, leleleadele commented on src/App.js
> +          <ProductList products={product} />
The naming implies it's one product though. I suggest to be aware that the naming is understandable to other devs if they look at your app. :)

2021-09-13 08:06 UTC, leleleadele approved these changes

2021-09-13 08:16 UTC, EgijaLocmele commented on src/App.js
> +          <ProductList products={product} />
Yeah maybe not the best example for the naming 😄

2021-09-13 08:33 UTC, YuraLeo94 requested changes

2021-09-13 08:33 UTC, YuraLeo94 commented on src/features/productDetails/ProductDetails.js
> +  return <ProductDetailsItem products={selectBook} />
Look like you have one `selectBook`, but `products` you have many why?

2021-09-13 08:33 UTC, YuraLeo94 commented on src/features/productDetails/ProductDetailsItem.js
> +  const { products } = props
Why `products`, but not `product`?

2021-09-13 08:33 UTC, YuraLeo94 commented on src/App.js
> +          <ProductList products={product} />
I agree with @leleleadele, rename please `product` to `products`

2021-09-13 08:37 UTC, YuraLeo94 commented on src/features/productDetails/ProductDetails.js
> +  return <ProductDetailsItem products={selectBook} />
Look like you have one `selectBook`, but `products` you have many why?

2021-09-13 09:17 UTC, Jose-Hash-Dev approved these changes

2021-09-13 09:55 UTC, YuraLeo94 approved these changes

2021-09-13 09:57 UTC, merged